- name: demo on  vars on play level veriable
  hosts: all
  vars: 
   URL: play.google.com
  tasks: 
    - name: demo on play variables
      debug: 
      msg: "URL = {{URL}}"
      


- name: demo on vars on task level veriable
  hosts: all
  tasks: 
   - name: demo for task level 
     debug: 
      msg: "URL = {{URL}}"
     vars: 
      URL: task.google.com 

   - name: access variable from previous task 
     debug: 
      msg: "URL = {{URL}}"         



      tower_settings90