- name: demo on  vars on play level veriable
  hosts: all
  vars: 
   URL: play.google.com
  tasks: 
    - name: demo on play variables
      debug: 
      msg: "URL = {{URL}}"
      


- name: demo on vars on task level veriable
  hosts: all
  tasks: 
   - name: demo for task level 
     debug: 
      msg: "URL = {{URL}}"
     vars: 
      URL: task.google.com 

   - name: access variable from previous task 
     debug: 
      msg: "URL = {{URL}}"         





- name : variable from prompt 
  hosts: 
  vars_prompt:
    - prompt: ENTER THE URL:- 
      name: URL
  tasks: 
    - name: demo on variable prompt
      debug: 
        msg: "URL = {{URL}}"    

